<!--START MODAL - ABOUT US-->
	<div id="modal_about_us" class="metro modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-header bg-red">
			<h3 id="myModalLabel">ABOUT US<i class="pull-right icon-cancel-2" style="margin-right:10px;" data-dismiss="modal"></i></h3>
		</div>
		<div class="modal-body">
		<!--BEGIN BODY MODAL CHARITIES-->
		 <div class="charities-container" style="padding:5px 10px 0px 10px;box-shadow: none;">
	<!-- Begin Item -->
	  <div class="charity-item">
		
	 <h4>About the S1 System</h4>
	<p>As a former Inspector, I came to realize that Every fatality CAN be avoided and every injury CAN be prevented….. It all comes down to the Three principles of safety: Recognition, Assessment and Control of hazards. Too many workers including young and vulnerable workers have a great disadvantage at work when it comes to Health and Safety and not surprisingly the lack of or limited training played a factor in 99% of my investigations. So we wondered, if workers and employers had access to affordable, easily accessible Health and Safety information in a language the workers understand and give workplace parties a proactive reason to learn and instruct their workers, could we reduce the number of injuries and fatalities?</p>
	<p>With your help, were about to find out...</p>
	<p>Introducing S1,</p>
	<p>The first worker and employer incentive based Digital Due Diligence system designed to raise the level of awareness of Health and Safety for its members in multiple languages while rewarding you for learning. The more you learn about Safety the more points you earn, the more points you earn the quicker you "Rank Up". The higher the rank, the better discounts you get at your favourite stores. Stay safe and earn discounts. It’s that easy!</p>  
	<p>Here at S1 we believe that ALL workplace parties have a Duty and Responsibility to ensure workers stay safe and employers meet their minimum requirements under the Occupational Health and Safety Act.  </p>
	<p>We're on a mission to make Health and Safety affordable, Exciting, engaging and quite simply, fun.</p>
	<p>We’re taking the gloves off in the fight for Health and Safety...</p>
	<p>Start exploring S1 today, You’ll be surprised at what you learn.</p>
	  </div>
	<!-- End Item -->

	<!-- Begin Item -->
	<a name="library"></a>
	  <div class="charity-item">
	<h4>About the Library</h4>
	<p>Our Library system was created by Health and Safety Professionals that care about the information that workers and employers receive in a language the workers understand. Our Library will be launching with the core fundamentals of Health and Safety in multiple languages and will be growing every month.</p>
	<p>Based on the industry and sector you’re in, the system will make recommendations for the information you need. Select, purchase, drag and drop, learn and earn points.</p>
	<p>Here at S1 we’re committed to bring you up-to-date relevant Health and Safety information at an affordable cost and raise the level of Health and Safety within your business.</p>
	<p>As a way to show that we haven’t forgotten those workers that have lost their lives at work, we will be donating 10% of all the revenue generated by the sales of our library content to Charity at every 20,000 members. The more downloads we have, the more we can help.</p>
	<p><a href="<?php echo $base;?>admin/libraries_metro?libtype=1" class="btn">Start Learning Today!...</a></p>		
	</div>
	<!-- End Item -->
	<a name="contact_about"></a>
	<div class="contact-form">
		<h3 class="page-title">Contact Us</h3>
		<p>Please fill out the contact form and we will get back to you as soon as possible:</p>
		  <form method="post" class="adminfrm" action="<?php echo $base."admin/contactusSendEmail?redirect_page=".$this->router->fetch_method();?>">
		  <div class="controls ">
		  <input class="span6" name="name" type="text" placeholder="Name" required />
		  <input class="span6" name="phone" type="text" placeholder="Phone" required/>
		  </div>
		  <div class="clear"></div>
		  <input id="email" name="email" class="span6" type="email" placeholder="Email"  required/>
		  <textarea name="message" class="span6" rows="6" placeholder="Message" required></textarea>
		  <input class="btn pull-right" type="submit" name="submit" value="Submit" />
		  </form>
	</div>
	</div>
		<!--END BODY MODAL CHARITIES-->  
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal">Close</button>
		</div>
	</div>
<!--END MODAL - ABOUT US-->
